version: '3.3'
services:
  web:
    image: tubes-1:latest
    ports:
      - 8008:80
  postgres_db:
    image: postgres:latest
    container_name: postgres_wbd
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=wbd_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_db:/var/lib/postgresql/data
volumes:
  postgres_db:
    driver: local
