version: "3.3"
services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_wbd
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
  php-apache-environment:
    container_name: php-apache
    volumes:
      - ./app:/var/www/html/
    ports:
      - "8000:80"
    depends_on:
      - postgres_db
    build:
      context: .
      dockerfile: Dockerfile
volumes:
  postgres_db:
    driver: local
