CREATE TABLE IF NOT EXISTS client
(
  client_id SERIAL PRIMARY KEY NOT NULL,
  username VARCHAR(50) NOT NULL UNIQUE,
  email VARCHAR(50) NOT NULL UNIQUE CHECK (email LIKE '%@%.%'),
  password VARCHAR(50) NOT NULL,
  admin_status BOOLEAN NOT NULL DEFAULT FALSE,
  birthdate DATE,
  bio TEXT,
  image VARCHAR(255)
);